chapter/syntax.tex

It might need some reformatting since I'm a Latex noob.
Also, I used `\widehat` instead of those square corners that we used in the lecture.

lecture 01 - indexed families and helper functions definitions - rough sketch

---

chapter/syntax.tex

I've tried to use better typesetting this time

Lecture 01 - syntax - classic approach

---

.github/workflows/build-latex.yml

Create releases using softprops/action-gh-release

---

chapter/syntax.tex

Added prose to 1.3

---

chapter/simpleTypes.tex

I addressed issues pointed out in last PR.

Amendments for "Simply Typed Lambda Calculus" section

---

chapter/syntax.tex

This might at least partially address #9 and #10.

Syntax: Add some prose to Sec. 1.1. and 1.2.

---

chapter/logicalRelations.tex

Logical Relations: Minor changes in 4.2.

---

chapter/logicalRelations.tex
macros.sty

Logical Relations: Add some prose to 4.3. and 4.4.

---

chapter/biorthogonality.tex
chapter/logicalRelations.tex
chapter/semantics.tex

Add prose to Sec. 4.5. and some motivation for biorthogonality

---

chapter/biorthogonality.tex
chapter/dataAbstraction.tex

Data Abstraction: Added technical stuff

---

chapter/semantics.tex

Add some prose to sections 2.1, 2.2, 2.3, 2.4. 
Add types of phi and psi in section 2.1. 
Improve phrasing and punctuation in sections 2.3 and 2.4.
Concerns issues #12 #13 #14 .

Semantics: prose and minor improvements

---

chapter/typeReconstruction.tex

I used `?X` etc. for unification variables (as in the lecture), which doesn't look good (IMO) in rendered pdf. Let me know if you want me to change it to something else.

Lecture 06 - definitions

---

chapter/logicalRelations.tex
chapter/polymorphism.tex

Fixes #56 and to a certain extent addresses #45.

Polymorphism: Added definitions and some prose to 6.2

---

chapter/typeReconstruction.tex

Type reconstruction: Fixed typo so the code compiles

---

chapter/typeReconstruction.tex
type-systems.tex

No issue, but noticed it missing so pieced together what i remembered from the lecture

ml-polymorphism subchapter

---

chapter/recursiveTypes.tex

I added an ascii art that should eventually be done using tikz.

Recursive Types: Added some prose to 9.1

---

chapter/polymorphism.tex

Add prose to beginning of chapter 6 and section 6.1.

---

chapter/biorthogonality.tex

Filled Section 5.1. with my lecture notes.
Ad. #42 .

Extended Section 5.1.

---

chapter/algebraicEffects.tex

I added more stuff from the lecture:
- an example use case, shown as a motivation for algebraic effects
- rules for effect polymorphism

extended chapter 13

---

chapter/dataAbstraction.tex
type-systems.tex

I wrote some explanation prose in 7.1.
(as required by #61)

some prose in section 7.1.
